/* eslint-disable react/jsx-no-comment-textnodes */
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Zeyada&display=swap" rel="stylesheet" /> */}
{/* <link  rel="preload" href="/Courgette-Regular.woff2" as="font" type="font/woff2" crossOrigin="anonymous" /> */}
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
